# Generated by Django 4.1 on 2024-04-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flavor', models.CharField(choices=[('caramel', 'Caramel'), ('vanilla', 'Vanilla'), ('hazelnut', 'Hazelnut'), ('cinnamon', 'Cinnamon')], max_length=20)),
                ('image', models.ImageField(upload_to='latte.jpeg/')),
            ],
        ),
    ]
