# Generated by Django 4.1 on 2024-04-17 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_medium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='latte',
            name='description',
        ),
        migrations.AlterField(
            model_name='latte',
            name='image',
            field=models.ImageField(upload_to='latte_images/'),
        ),
        migrations.AddField(
            model_name='latte',
            name='size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='store.size'),
            preserve_default=False,
        ),
    ]
