# Generated by Django 4.1 on 2024-04-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_size_remove_latte_description_alter_latte_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latte',
            name='price',
        ),
        migrations.AlterField(
            model_name='latte',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
