# Generated by Django 4.1 on 2024-04-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_latte_price_alter_latte_size_delete_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latte',
            name='image',
        ),
        migrations.RemoveField(
            model_name='latte',
            name='name',
        ),
        migrations.AddField(
            model_name='latte',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='latte',
            name='flavor',
            field=models.CharField(choices=[('vanilla', 'Vanilla'), ('caramel', 'Caramel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='latte',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
    ]
