# Generated by Django 4.1 on 2024-04-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
