# Generated by Django 4.1 on 2024-04-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_temporarycartitem_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryCartItem',
        ),
    ]
