# Generated by Django 4.1 on 2024-04-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_temporarycartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macchiato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('flavor', models.CharField(choices=[('caramel', 'Caramel'), ('vanilla', 'Vanilla'), ('hazelnut', 'Hazelnut'), ('cinnamon', 'Cinnamon')], max_length=20)),
                ('image', models.ImageField(upload_to='macchiato_images/')),
            ],
        ),
    ]
