# Generated by Django 4.1 on 2024-04-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_macchiato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cappuccino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('flavor', models.CharField(choices=[('Caramel', 'Caramel'), ('Vanilla', 'Vanilla'), ('Hazelnut', 'Hazelnut'), ('Cinnamon', 'Cinnamon')], max_length=20)),
                ('image', models.ImageField(upload_to='cappuccino_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='latte',
            name='flavor',
            field=models.CharField(choices=[('Caramel', 'Caramel'), ('Vanilla', 'Vanilla'), ('Hazelnut', 'Hazelnut'), ('Cinnamon', 'Cinnamon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='macchiato',
            name='flavor',
            field=models.CharField(choices=[('Caramel', 'Caramel'), ('Vanilla', 'Vanilla'), ('Hazelnut', 'Hazelnut'), ('Cinnamon', 'Cinnamon')], max_length=20),
        ),
    ]
