# Generated by Django 4.1 on 2024-04-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cappuccino_alter_latte_flavor_alter_macchiato_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('image', models.ImageField(upload_to='espresso_images/')),
            ],
        ),
    ]
