# Generated by Django 4.1 on 2024-04-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_espresso_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalGlaze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='donut_images/')),
            ],
        ),
    ]
