# Generated by Django 4.1 on 2024-04-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_originalglaze'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalglaze',
            name='flavor',
            field=models.CharField(choices=[('Original', 'Original')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originalglaze',
            name='size',
            field=models.CharField(choices=[('regular', 'Regular'), ('donutHole', 'Donut Hole')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='originalglaze',
            name='image',
            field=models.ImageField(upload_to='original_images/'),
        ),
    ]
