# Generated by Django 4.1 on 2024-04-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_strawberry_alter_originalglaze_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strawberry',
            name='image',
            field=models.ImageField(upload_to='Strawberry_images/'),
        ),
    ]
