# Generated by Django 4.1 on 2024-04-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_chocolate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BostonCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20)),
                ('flavor', models.CharField(choices=[('Boston Cream', 'Boston Cream')], max_length=20)),
                ('image', models.ImageField(upload_to='BostonCream_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='size',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20),
        ),
        migrations.AlterField(
            model_name='originalglaze',
            name='size',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20),
        ),
        migrations.AlterField(
            model_name='strawberry',
            name='size',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vanilla',
            name='size',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20),
        ),
    ]
