# Generated by Django 4.1 on 2024-04-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_bostoncream_alter_chocolate_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JellyDonut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20)),
                ('flavor', models.CharField(choices=[('Jelly', 'Jelly')], max_length=20)),
                ('image', models.ImageField(upload_to='JellyDonut_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MapleBacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20)),
                ('flavor', models.CharField(choices=[('Maple Bacon', 'Maple Bacon')], max_length=20)),
                ('image', models.ImageField(upload_to='MapleBacon_images/')),
            ],
        ),
    ]
