# Generated by Django 4.1 on 2024-04-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_cruller_smore'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueberryCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20)),
                ('flavor', models.CharField(choices=[('Blueberry Cake', 'Blueberry Cake')], max_length=20)),
                ('image', models.ImageField(upload_to='BlueberryCake_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PBNJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('Regular', 'Regular'), ('Donut Hole', 'Donut Hole')], max_length=20)),
                ('flavor', models.CharField(choices=[('PBNJ', 'PBNJ')], max_length=20)),
                ('image', models.ImageField(upload_to='PBNJ_images/')),
            ],
        ),
    ]
