# Generated by Django 4.1 on 2024-04-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_blueberrycake_pbnj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueberrycake',
            name='flavor',
            field=models.CharField(choices=[('Blueberry Cake', 'Blueberry Cake'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bostoncream',
            name='flavor',
            field=models.CharField(choices=[('Boston Cream', 'Boston Cream'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='flavor',
            field=models.CharField(choices=[('Chocolate', 'Chocolate'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cruller',
            name='flavor',
            field=models.CharField(choices=[('Cruller', 'Cruller'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jellydonut',
            name='flavor',
            field=models.CharField(choices=[('Jelly', 'Jelly'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maplebacon',
            name='flavor',
            field=models.CharField(choices=[('Maple Bacon', 'Maple Bacon'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='originalglaze',
            name='flavor',
            field=models.CharField(choices=[('Original', 'Original'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pbnj',
            name='flavor',
            field=models.CharField(choices=[('PBNJ', 'PBNJ'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smore',
            name='flavor',
            field=models.CharField(choices=[('Smore', 'Smore'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='strawberry',
            name='flavor',
            field=models.CharField(choices=[('Strawberry', 'Strawberry'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vanilla',
            name='flavor',
            field=models.CharField(choices=[('Vanilla', 'Vanilla'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free')], max_length=20),
        ),
    ]
